// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package gendb

import (
	"encoding/json"

	"github.com/google/uuid"
)

type Drone struct {
	ID      int64
	Name    string
	Address string
	Ip      string
	Status  bool
}

type Mission struct {
	ID          int64
	Name        string
	DroneID     int64
	PackageID   int64
	SeqID       int64
	ImageFolder string
	Status      string
}

type Package struct {
	ID         int64
	Name       string
	Weight     float64
	Height     float64
	Length     float64
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
}

type Sequence struct {
	ID          int64
	Name        string
	Description string
	Seq         json.RawMessage
	Length      int64
}

type User struct {
	ID   uuid.UUID
	Name string
}
