// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package gendb

import (
	"database/sql"
)

type Mission struct {
	ID        int64
	Protobuf  sql.NullString
	CreatedAt sql.NullTime
}
