// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package gendb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/tabbed/pqtype"
)

type Drone struct {
	ID      uuid.UUID
	Name    string
	Address string
	Status  bool
}

type Mission struct {
	ID        int64
	Name      string
	DroneID   uuid.UUID
	PackageID uuid.UUID
	SeqID     int64
}

type Package struct {
	ID         uuid.UUID
	Name       string
	Weight     float64
	Height     float64
	Length     float64
	SenderID   uuid.UUID
	ReceiverID uuid.UUID
}

type Sequence struct {
	ID          int64
	Name        sql.NullString
	Description sql.NullString
	Seq         pqtype.NullRawMessage
	CreatedAt   time.Time
}

type User struct {
	ID   uuid.UUID
	Name string
}
